version: "3.9"
services:
  neural-pixel-web:
    build: .
    image: neural-pixel-web:latest
    container_name: neural-pixel-web
    ports:
      - "7860:7860"
    environment:
      - MODELS_DIR=/app/models
      - OUTPUTS_DIR=/app/outputs
    volumes:
      - ./models:/app/models:ro
      - ./outputs:/app/outputs
      - ./sd:/app/sd:ro
      - ./sd-cpu:/app/sd-cpu:ro
    device_requests:
      - driver: nvidia
        count: -1
        capabilities: [["gpu"]]
