version: "3.9"
services:
  neural-pixel-web:
    image: ghcr.io/agusalex/neural-pixel:latest
    container_name: neural-pixel-web
    ports:
      - "7860:7860"
    environment:
      - MODELS_DIR=/app/models
      - OUTPUTS_DIR=/app/outputs
    volumes:
      - ./models:/app/models:ro
      - ./outputs:/app/outputs
    # sd and sd-cpu are now baked into the image; no need to mount them
    # For NVIDIA GPUs; remove if not needed
    device_requests:
      - driver: nvidia
        count: -1
        capabilities: [["gpu"]]
